# Site
repository: LeonShangguan/LeonShangguan.github.io
favicon: images/lemon.jpeg

# Personal info
name: Zhongkai(Leon) Shangguan
title: Master Student at University of Rochester
email: zshangg2@ur.rochester.edu
phone: (585) 981-6779
website: leonshangguan.work

darkmode: true

# Social links
github_username:  LeonShangguan
linkedin_username: zhongkai-leon-shangguan-52b465152
kaggle_username: LeonShangguan

# Additional icon links
# additional_links:
# - title: Kaggle
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/LeonPhoto.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Zhongkai Shangguan, you can also call me Leon. I'm now a Master student in 
  [Department of Electrical and Computer Engineering](http://www.hajim.rochester.edu/ece/),
  [University of Rochester](https://www.rochester.edu/). I'm also a research assitant in 
  [Rochester Data Science Consortium](http://rocdatascience.com/). My research interests is 
  <mark>Image Processing</mark>, mainly for image segmentation, include some kind of Computer Vision. 
  I'm also interested in <mark>Data Science</mark>, focus on reinforcement learning (DDPG).
  

# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  **Skills**:
  Python, matlab, Java, HTML.
  **Interests**:
  Basketball, League of Legend,
# This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

# Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
